import Head from 'next/head';

import { Hero, Features, Services } from '../components';

const HomePage: React.FC = () => {
	return (
		<div>
			<Head>
				<title>CDY | Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />
			<Features />
			<Services />
		</div>
	);
};

export default HomePage;
